@startuml
!pragma useVerticalIf on
start

partition Handle "use" {
    if (item is "key") then (yes)
        if ("key" in taken_items) then (yes)
            if (location is "door") then (yes)
                :set door_state = "unlocked";
                :set action_description = "You insert the key... bla... the door unlucks";
            else (no)
                :set action_description = "There is no keyhole here";
            endif
        else (no)
            :set action_description = "You don't have a key";
        endif
    else (no)
        :set action_description = "You cannot use that (//item//);
    endif
}

stop
@enduml